// Generated by gencpp from file pkg1/AddTwoInts.msg
// DO NOT EDIT!


#ifndef PKG1_MESSAGE_ADDTWOINTS_H
#define PKG1_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <pkg1/AddTwoIntsRequest.h>
#include <pkg1/AddTwoIntsResponse.h>


namespace pkg1
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace pkg1


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pkg1::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::pkg1::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::pkg1::AddTwoInts > {
  static const char* value()
  {
    return "pkg1/AddTwoInts";
  }

  static const char* value(const ::pkg1::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::pkg1::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::pkg1::AddTwoInts >
template<>
struct MD5Sum< ::pkg1::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pkg1::AddTwoInts >::value();
  }
  static const char* value(const ::pkg1::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pkg1::AddTwoIntsRequest> should match
// service_traits::DataType< ::pkg1::AddTwoInts >
template<>
struct DataType< ::pkg1::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::pkg1::AddTwoInts >::value();
  }
  static const char* value(const ::pkg1::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pkg1::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::pkg1::AddTwoInts >
template<>
struct MD5Sum< ::pkg1::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pkg1::AddTwoInts >::value();
  }
  static const char* value(const ::pkg1::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pkg1::AddTwoIntsResponse> should match
// service_traits::DataType< ::pkg1::AddTwoInts >
template<>
struct DataType< ::pkg1::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::pkg1::AddTwoInts >::value();
  }
  static const char* value(const ::pkg1::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PKG1_MESSAGE_ADDTWOINTS_H
