(cl:defpackage tiburon_task_trainee-srv
  (:use )
  (:export
   "ADDTWOINTS"
   "<ADDTWOINTS-REQUEST>"
   "ADDTWOINTS-REQUEST"
   "<ADDTWOINTS-RESPONSE>"
   "ADDTWOINTS-RESPONSE"
   "COMPLEXOPERATION"
   "<COMPLEXOPERATION-REQUEST>"
   "COMPLEXOPERATION-REQUEST"
   "<COMPLEXOPERATION-RESPONSE>"
   "COMPLEXOPERATION-RESPONSE"
  ))

