// Generated by gencpp from file tiburon_task_trainee/AddTwoInts.msg
// DO NOT EDIT!


#ifndef TIBURON_TASK_TRAINEE_MESSAGE_ADDTWOINTS_H
#define TIBURON_TASK_TRAINEE_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <tiburon_task_trainee/AddTwoIntsRequest.h>
#include <tiburon_task_trainee/AddTwoIntsResponse.h>


namespace tiburon_task_trainee
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace tiburon_task_trainee


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tiburon_task_trainee::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::tiburon_task_trainee::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::tiburon_task_trainee::AddTwoInts > {
  static const char* value()
  {
    return "tiburon_task_trainee/AddTwoInts";
  }

  static const char* value(const ::tiburon_task_trainee::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::tiburon_task_trainee::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::tiburon_task_trainee::AddTwoInts >
template<>
struct MD5Sum< ::tiburon_task_trainee::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tiburon_task_trainee::AddTwoInts >::value();
  }
  static const char* value(const ::tiburon_task_trainee::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tiburon_task_trainee::AddTwoIntsRequest> should match
// service_traits::DataType< ::tiburon_task_trainee::AddTwoInts >
template<>
struct DataType< ::tiburon_task_trainee::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::tiburon_task_trainee::AddTwoInts >::value();
  }
  static const char* value(const ::tiburon_task_trainee::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tiburon_task_trainee::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::tiburon_task_trainee::AddTwoInts >
template<>
struct MD5Sum< ::tiburon_task_trainee::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tiburon_task_trainee::AddTwoInts >::value();
  }
  static const char* value(const ::tiburon_task_trainee::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tiburon_task_trainee::AddTwoIntsResponse> should match
// service_traits::DataType< ::tiburon_task_trainee::AddTwoInts >
template<>
struct DataType< ::tiburon_task_trainee::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::tiburon_task_trainee::AddTwoInts >::value();
  }
  static const char* value(const ::tiburon_task_trainee::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TIBURON_TASK_TRAINEE_MESSAGE_ADDTWOINTS_H
