// Generated by gencpp from file tiburon_task_trainee/complexOperation.msg
// DO NOT EDIT!


#ifndef TIBURON_TASK_TRAINEE_MESSAGE_COMPLEXOPERATION_H
#define TIBURON_TASK_TRAINEE_MESSAGE_COMPLEXOPERATION_H

#include <ros/service_traits.h>


#include <tiburon_task_trainee/complexOperationRequest.h>
#include <tiburon_task_trainee/complexOperationResponse.h>


namespace tiburon_task_trainee
{

struct complexOperation
{

typedef complexOperationRequest Request;
typedef complexOperationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct complexOperation
} // namespace tiburon_task_trainee


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tiburon_task_trainee::complexOperation > {
  static const char* value()
  {
    return "7adffa4ba6f9b8e2c7b72794812fa152";
  }

  static const char* value(const ::tiburon_task_trainee::complexOperation&) { return value(); }
};

template<>
struct DataType< ::tiburon_task_trainee::complexOperation > {
  static const char* value()
  {
    return "tiburon_task_trainee/complexOperation";
  }

  static const char* value(const ::tiburon_task_trainee::complexOperation&) { return value(); }
};


// service_traits::MD5Sum< ::tiburon_task_trainee::complexOperationRequest> should match
// service_traits::MD5Sum< ::tiburon_task_trainee::complexOperation >
template<>
struct MD5Sum< ::tiburon_task_trainee::complexOperationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tiburon_task_trainee::complexOperation >::value();
  }
  static const char* value(const ::tiburon_task_trainee::complexOperationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tiburon_task_trainee::complexOperationRequest> should match
// service_traits::DataType< ::tiburon_task_trainee::complexOperation >
template<>
struct DataType< ::tiburon_task_trainee::complexOperationRequest>
{
  static const char* value()
  {
    return DataType< ::tiburon_task_trainee::complexOperation >::value();
  }
  static const char* value(const ::tiburon_task_trainee::complexOperationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tiburon_task_trainee::complexOperationResponse> should match
// service_traits::MD5Sum< ::tiburon_task_trainee::complexOperation >
template<>
struct MD5Sum< ::tiburon_task_trainee::complexOperationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tiburon_task_trainee::complexOperation >::value();
  }
  static const char* value(const ::tiburon_task_trainee::complexOperationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tiburon_task_trainee::complexOperationResponse> should match
// service_traits::DataType< ::tiburon_task_trainee::complexOperation >
template<>
struct DataType< ::tiburon_task_trainee::complexOperationResponse>
{
  static const char* value()
  {
    return DataType< ::tiburon_task_trainee::complexOperation >::value();
  }
  static const char* value(const ::tiburon_task_trainee::complexOperationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TIBURON_TASK_TRAINEE_MESSAGE_COMPLEXOPERATION_H
